/* Configuration for hello generated by Alire */
#ifndef HELLO_CONFIG_H
#define HELLO_CONFIG_H

#define CRATE_VERSION "1.0.2"
#define CRATE_NAME "hello"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
